exclude: ['lamu.sublime-project', 'lamu.sublime-workspace']
include: ['*.scss']
site_name: Ushahidi 3.0 - Lamu
tagline: Ushahidi Platform 3.0
# needs front slash because of base URL
css: /css/global.css
# this allows for correct gh-pages urls
baseurl: /_site
